// Generated by tools/path_planner.py -- paste into an autonomous routine.
// Coordinates: inches, origin at field centre, heading 0 = +y, clockwise +.
chassis.turnToPoint(0.00, 50.00, 2000, {.forwards = true, .direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 1: turnToPoint (0.0, 50.0) 2000ms
chassis.waitUntilDone();  // 2: waitUntilDone
chassis.turnToHeading(90.00, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 3: turnToHeading hdg 90.0 2000ms
chassis.waitUntilDone();  // 4: waitUntilDone
chassis.turnToPoint(0.00, 20.00, 2000, {.forwards = true, .direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 5: turnToPoint (0.0, 20.0) 2000ms
chassis.waitUntilDone();  // 6: waitUntilDone
