// Generated by tools/path_planner.py -- paste into an autonomous routine.
// Coordinates: inches, origin at field centre, heading 0 = +y, clockwise +.
//
// Planned against this robot configuration (src/main.cpp):
//   lemlib::Drivetrain drivetrain(&left_motor_group, &right_motor_group, 15, lemlib::Omniwheel::NEW_325, 458, 2);
//   lemlib::OdomSensors sensors(nullptr, nullptr, nullptr, nullptr, &imu);
//   lemlib::ControllerSettings lateral_controller(10, 0, 28, 3, 1, 100, 3, 500, 20);
//   lemlib::ControllerSettings angular_controller(5.60, 0.001, 28.590, 0, 0, 0, 0, 0, 0);
//   lemlib::Chassis chassis(drivetrain, lateral_controller, angular_controller, sensors, &throttle_curve, &steer_curve);
//
//   lateral (drive)  kP 10  kI 0  kD 28  windup 3
//                    exit: small 1 for 100 ms, large 3 for 500 ms, slew 20
//   angular (turn)   kP 5.6  kI 0.001  kD 28.59  windup 0
//                    exit: small 0 for 0 ms, large 0 for 0 ms, slew 0

// Calibrates the IMU and starts odometry. It blocks for ~3 s and the
// robot must be still and untouched while it runs. initialize() already
// calibrates on startup, so drop this line if the robot has been sitting
// since then -- it re-zeroes the heading, hence the setPose below it.
chassis.calibrate();
chassis.setPose(0.90, -65.40, 359.30);  // start pose

chassis.moveToPoint(0.60, -41.20, 2000, {.forwards = true, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 1: moveToPoint (0.6, -41.2) 2000ms
chassis.waitUntilDone();  // 2: waitUntilDone
chassis.turnToHeading(303.16, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 3: turnToHeading hdg 303.2 2000ms
chassis.waitUntilDone();  // 4: waitUntilDone
chassis.moveToPoint(-36.90, -16.70, 2000, {.forwards = true, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 5: moveToPoint (-36.9, -16.7) 2000ms
chassis.waitUntilDone();  // 6: waitUntilDone
chassis.turnToHeading(3.78, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 7: turnToHeading hdg 3.8 2000ms
chassis.waitUntilDone();  // 8: waitUntilDone
chassis.moveToPoint(-34.60, 18.10, 2000, {.forwards = true, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 9: moveToPoint (-34.6, 18.1) 2000ms
chassis.waitUntilDone();  // 10: waitUntilDone
chassis.turnToHeading(232.01, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 11: turnToHeading hdg 232.0 2000ms
chassis.waitUntilDone();  // 12: waitUntilDone
chassis.moveToPoint(-61.10, -2.60, 2000, {.forwards = true, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 13: moveToPoint (-61.1, -2.6) 2000ms
chassis.waitUntilDone();  // 14: waitUntilDone
