// Generated by tools/path_planner.py -- paste into an autonomous routine.
// Coordinates: inches, origin at field centre, heading 0 = +y, clockwise +.
chassis.turnToHeading(0.00, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 1: turnToHeading hdg 0.0 2000ms
chassis.turnToPoint(0.00, 0.00, 2000, {.forwards = true, .direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 2: turnToPoint (0.0, 0.0) 2000ms
pros::delay(500);  // 3: wait 500 ms
chassis.swingToHeading(0.00, lemlib::DriveSide::LEFT, 2000, {.direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 4: swingToHeading hdg 0.0 LEFT 2000ms
chassis.swingToPoint(0.00, 0.00, lemlib::DriveSide::LEFT, 2000, {.forwards = true, .direction = lemlib::AngularDirection::AUTO, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 5: swingToPoint (0.0, 0.0) LEFT 2000ms
chassis.moveToPoint(0.00, 0.00, 2000, {.forwards = true, .maxSpeed = 127, .minSpeed = 0, .earlyExitRange = 0.00});  // 6: moveToPoint (0.0, 0.0) 2000ms
pros::delay(500);  // 7: wait 500 ms
